### ISSUE TITLE
Mechanical vs electronic PEEP

### ISSUE THREAD

**Issue by cmfsx** [librerespire/ventilator#19]
P3 PEEP is not relevant if the PEEP valve is mechanical. P3 PEEP should be included in the loop when electronically controlled PEEP valve is used. 

https://github.com/librerespire/ventilator/blob/519f6ead6bdfed8257125dfd74dad3634d3425b2/Firmware/RaspberryPi/backend-pi/Controller.py#L204

**Comment by chamrepo** [comment]
Controlling pressure was made out of scope for this mode
